import { StyleSheet } from '@react-pdf/renderer'

export const COLORS = {
  pink:        '#F472B6',
  pinkLight:   '#FCE7F3',
  pinkPale:    '#FFF0F8',
  purple:      '#A855F7',
  purpleLight: '#F3E8FF',
  blue:        '#60A5FA',
  blueLight:   '#EFF6FF',
  yellow:      '#FBBF24',
  yellowLight: '#FFFBEB',
  green:       '#34D399',
  greenLight:  '#ECFDF5',
  white:       '#FFFFFF',
  gray50:      '#F9FAFB',
  gray100:     '#F3F4F6',
  gray300:     '#D1D5DB',
  gray400:     '#9CA3AF',
  gray600:     '#4B5563',
  gray700:     '#374151',
  gray800:     '#1F2937',
}

export const CATEGORY_COLORS = {
  birthdays:    { bg: COLORS.pinkLight,   accent: COLORS.pink,   text: '#BE185D' },
  milestones:   { bg: COLORS.purpleLight, accent: COLORS.purple, text: '#7E22CE' },
  funnyHabits:  { bg: COLORS.yellowLight, accent: COLORS.yellow, text: '#92400E' },
  memories:     { bg: COLORS.blueLight,   accent: COLORS.blue,   text: '#1E40AF' },
  achievements: { bg: COLORS.greenLight,  accent: COLORS.green,  text: '#065F46' },
}

export const styles = StyleSheet.create({
  // ── Page ──────────────────────────────────────────
  page: {
    fontFamily: 'Inter',
    backgroundColor: COLORS.white,
    paddingTop: 40,
    paddingBottom: 50,
    paddingHorizontal: 44,
  },

  // ── Cover ─────────────────────────────────────────
  coverPage: {
    fontFamily: 'Inter',
    backgroundColor: COLORS.pinkPale,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  coverPhotoContainer: {
    width: '100%',
    height: 360,
    overflow: 'hidden',
    backgroundColor: COLORS.pinkLight,
  },
  coverPhoto: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  coverGradientFallback: {
    width: '100%',
    height: 360,
    backgroundColor: COLORS.pinkLight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverFallbackEmoji: {
    fontSize: 80,
    color: COLORS.pink,
  },
  coverContent: {
    flex: 1,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 48,
    paddingVertical: 32,
  },
  coverBookLabel: {
    fontFamily: 'Nunito',
    fontSize: 11,
    fontWeight: 700,
    color: COLORS.pink,
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  coverBabyName: {
    fontFamily: 'Nunito',
    fontSize: 42,
    fontWeight: 800,
    color: COLORS.gray800,
    textAlign: 'center',
    marginBottom: 8,
  },
  coverSubtitle: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: COLORS.gray400,
    textAlign: 'center',
    marginBottom: 6,
  },
  coverDivider: {
    width: 60,
    height: 3,
    backgroundColor: COLORS.pink,
    borderRadius: 2,
    marginTop: 16,
    marginBottom: 16,
  },
  coverStats: {
    fontFamily: 'Inter',
    fontSize: 11,
    color: COLORS.gray400,
    textAlign: 'center',
  },

  // ── Age section divider page ───────────────────────
  sectionPage: {
    fontFamily: 'Inter',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 56,
    paddingVertical: 60,
  },
  sectionAccentBar: {
    width: 6,
    height: 56,
    backgroundColor: COLORS.pink,
    borderRadius: 3,
    marginBottom: 20,
  },
  sectionSuperLabel: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: COLORS.pink,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  sectionAgeLabel: {
    fontFamily: 'Nunito',
    fontSize: 48,
    fontWeight: 800,
    color: COLORS.gray800,
    marginBottom: 8,
    lineHeight: 1.1,
  },
  sectionDescription: {
    fontFamily: 'Inter',
    fontSize: 12,
    color: COLORS.gray400,
  },
  sectionCountBadge: {
    marginTop: 24,
    backgroundColor: COLORS.pinkLight,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionCountText: {
    fontFamily: 'Nunito',
    fontWeight: 700,
    fontSize: 12,
    color: COLORS.pink,
  },

  // ── Category section ──────────────────────────────
  categoryHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
    paddingBottom: 6,
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.gray100,
  },
  categoryAccentDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  categoryLabel: {
    fontFamily: 'Nunito',
    fontWeight: 700,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  categoryCount: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: COLORS.gray400,
    marginLeft: 6,
  },

  // ── Entry block ───────────────────────────────────
  entryBlock: {
    marginBottom: 14,
    paddingLeft: 12,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.gray100,
  },
  entryTitleRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  entryTitle: {
    fontFamily: 'Nunito',
    fontWeight: 700,
    fontSize: 12,
    color: COLORS.gray800,
    flex: 1,
  },
  entryDate: {
    fontFamily: 'Inter',
    fontSize: 9,
    color: COLORS.gray400,
    marginLeft: 8,
    flexShrink: 0,
  },
  entryCaption: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: COLORS.gray600,
    fontStyle: 'italic',
    marginBottom: 4,
  },
  entryNotes: {
    fontFamily: 'Inter',
    fontSize: 10,
    color: COLORS.gray700,
    lineHeight: 1.55,
    marginBottom: 6,
  },

  // ── Photo grid ────────────────────────────────────
  photoGrid1: {
    width: '100%',
    height: 160,
    borderRadius: 6,
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 4,
  },
  photoGrid2: {
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
    marginBottom: 4,
    height: 120,
  },
  photoGrid3: {
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
    marginBottom: 4,
    height: 100,
  },
  photoGrid4: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
    marginBottom: 4,
  },
  photo: {
    objectFit: 'cover',
    borderRadius: 5,
  },

  // ── Page number footer ────────────────────────────
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontFamily: 'Inter',
    fontSize: 9,
    color: COLORS.gray300,
  },
})
